processes: 5

VGsim:
  rate_file: VGsim/example/example.rt
  iterations: 10000
  pp_population_model_file: VGsim/example/example.pp
  mg_population_model_file: VGsim/example/example.mg
  seed: 2020
  sample_size: 5

phastSim:
  tree_file: newick_output.nwk
  reference_genome: reference_genome.fasta
  output_dir: phastSim_output
  seed: 7

split_amplicons:
  primer_sequences: "V3/nCoV-2019.tsv"
  primer_positions: "V3/nCoV-2019.primer.bed"
  random_dropout_probability: 0.001
  match_coverage_mean: 500
  match_coverage_sd: 20
  mismatch_coverage_mean: 5
  mismatch_coverage_sd: 1

viridian_workflow:
  primer_bed: "V3/nCoV-artic-v3.bed"