threads: 64
reference_genome: reference_genome.fasta
divide_genomes: False
proportion_illumina: 0.90
primer_scheme: V4
primer_scheme_dir: https://github.com/artic-network/primer-schemes
seed: 2022
container_directory: singularity

VGsim:
  rate_file: VGsim_params/rate_file.rt
  iterations: 10000000
  pp_population_model_file: VGsim_params/pp_population.pp
  mg_population_model_file: VGsim_params/mg_population.mg
  sample_size: 10000

phastSim:
  tree_file: newick_output.nwk
  output_dir: phastSim_output
  substitution_rate: 0.0002

split_amplicons:
  random_dropout_probability: 0.001
  primer_dimer_probability: 0.001
  match_coverage_mean: 500
  match_coverage_sd: 20
  mismatch_coverage_mean: 5
  mismatch_coverage_sd: 1

simulate_reads:
  illumina_read_length: 250

artic_assemble:
  nextflow_path: nextflow
  illumina_workflow_container: singularity/ncov2019-artic-nf/artic-ncov2019-illumina.sif
  nanopore_workflow_container: singularity/ncov2019-artic-nf/artic-ncov2019-nanopore.sif

mask_assemblies:
  apply_mask: False

phylogenies:
  batch_size: 20